"""Canvas integration: institution registry and the stateless read-only adapter."""

from .adapter import (
    ALLOWED_ENDPOINTS,
    CanvasCourse,
    CanvasFileEntry,
    CanvasProfile,
    CanvasReadAdapter,
    CanvasReadError,
    DownloadResult,
    parse_next_link,
)
from .http_safety import (
    UnsafeUrlError,
    is_public_address,
    normalize_origin,
    resolve_public_host,
    validate_api_url,
    validate_download_target,
)
from .oauth import (
    AuthorizationState,
    CanvasOAuthClient,
    CompletedAuthorization,
    Connection,
    CredentialStore,
    InMemoryCredentialStore,
    InMemoryStateStore,
    OAuthError,
    StateStore,
    StoredCredential,
    TokenSet,
    callback_matches_institution,
    scopes_for,
    token_provider_for,
)
from .registry import (
    AVAILABLE,
    NOT_CONFIGURED,
    Institution,
    InstitutionConnectionRegistry,
    UnknownInstitutionError,
    default_institutions,
)

__all__ = [
    "ALLOWED_ENDPOINTS",
    "AVAILABLE",
    "AuthorizationState",
    "CanvasCourse",
    "CanvasFileEntry",
    "CanvasOAuthClient",
    "CanvasProfile",
    "CanvasReadAdapter",
    "CanvasReadError",
    "CompletedAuthorization",
    "Connection",
    "CredentialStore",
    "DownloadResult",
    "InMemoryCredentialStore",
    "InMemoryStateStore",
    "Institution",
    "InstitutionConnectionRegistry",
    "NOT_CONFIGURED",
    "OAuthError",
    "StateStore",
    "StoredCredential",
    "TokenSet",
    "UnknownInstitutionError",
    "UnsafeUrlError",
    "callback_matches_institution",
    "default_institutions",
    "is_public_address",
    "normalize_origin",
    "parse_next_link",
    "resolve_public_host",
    "scopes_for",
    "token_provider_for",
    "validate_api_url",
    "validate_download_target",
]
