"""Canvas integration: institution registry and the stateless read-only adapter."""

from .adapter import (
    ALLOWED_ENDPOINTS,
    CanvasCourse,
    CanvasFileEntry,
    CanvasProfile,
    CanvasReadAdapter,
    CanvasReadError,
    DownloadResult,
    parse_next_link,
)
from .http_safety import (
    UnsafeUrlError,
    is_public_address,
    normalize_canvas_page_origin,
    normalize_origin,
    resolve_public_host,
    validate_api_url,
    validate_download_target,
)
from .job import (
    ALL_STATES,
    TERMINAL_STATES,
    FileRecord,
    ImportJob,
    JobStateError,
    new_job,
    selection_fingerprint,
)
from .oauth import (
    AuthorizationState,
    CanvasOAuthClient,
    CompletedAuthorization,
    Connection,
    CredentialStore,
    InMemoryCredentialStore,
    InMemoryStateStore,
    OAuthError,
    StateStore,
    StoredCredential,
    TokenSet,
    callback_matches_institution,
    scopes_for,
    token_provider_for,
)
from .registry import (
    AVAILABLE,
    NOT_CONFIGURED,
    Institution,
    InstitutionConnectionRegistry,
    UnknownInstitutionError,
    default_institutions,
)
from .store import CanvasJobRepository, ClaimedJob
from .transient_credential import (
    DESTROYED,
    EXPIRED,
    LOST_ON_RESTART,
    NEVER_STORED,
    PRESENT_TRANSIENTLY,
    CredentialRefused,
    CredentialUnavailable,
    TaskCredential,
    TransientCanvasCredentialStore,
)
from .worker import (
    CanvasImportWorker,
    RunResult,
    default_target_course_resolver,
    material_media_type,
    safe_upload_name,
    target_course_slug,
)
from .worker_decisions import (
    FileOutcome,
    outcome_for_download,
    outcome_for_error,
    should_stop_job,
)

__all__ = [
    "ALLOWED_ENDPOINTS",
    "AVAILABLE",
    "AuthorizationState",
    "CanvasCourse",
    "CanvasFileEntry",
    "CanvasOAuthClient",
    "CanvasProfile",
    "CanvasReadAdapter",
    "CanvasReadError",
    "CompletedAuthorization",
    "Connection",
    "CredentialStore",
    "DownloadResult",
    "InMemoryCredentialStore",
    "InMemoryStateStore",
    "Institution",
    "InstitutionConnectionRegistry",
    "NOT_CONFIGURED",
    "OAuthError",
    "StateStore",
    "StoredCredential",
    "TokenSet",
    "UnknownInstitutionError",
    "UnsafeUrlError",
    "callback_matches_institution",
    "default_institutions",
    "is_public_address",
    "normalize_canvas_page_origin",
    "normalize_origin",
    "parse_next_link",
    "resolve_public_host",
    "scopes_for",
    "token_provider_for",
    "validate_api_url",
    "validate_download_target",
    # import-job core (job.py), its persistence (store.py) and the worker's decisions
    "ALL_STATES",
    "TERMINAL_STATES",
    "FileRecord",
    "ImportJob",
    "JobStateError",
    "new_job",
    "selection_fingerprint",
    "CanvasJobRepository",
    "ClaimedJob",
    "FileOutcome",
    "outcome_for_download",
    "outcome_for_error",
    "should_stop_job",
    # the worker that drives the state machine (worker.py)
    "CanvasImportWorker",
    "RunResult",
    "default_target_course_resolver",
    "material_media_type",
    "safe_upload_name",
    "target_course_slug",
    # the credential that lives for one task and is then destroyed
    # (transient_credential.py)
    "DESTROYED",
    "EXPIRED",
    "LOST_ON_RESTART",
    "NEVER_STORED",
    "PRESENT_TRANSIENTLY",
    "CredentialRefused",
    "CredentialUnavailable",
    "TaskCredential",
    "TransientCanvasCredentialStore",
]
