-- Automatic whole-course builds are metered separately from learner turns.
--
-- The reservation remains mandatory for every provider dispatch, but a large
-- frozen corpus must not consume (or be stopped by) the learner's interactive
-- daily-call allowance.  SQLite's ADD COLUMN has no IF NOT EXISTS, so db.py
-- adds quota_scope under a table_info guard after this ledger migration.

CREATE TABLE IF NOT EXISTS auto_knowledge_job_recovery_receipts (
    id TEXT PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES auto_knowledge_jobs(id) ON DELETE RESTRICT,
    reason TEXT NOT NULL CHECK(reason IN (
        'BACKGROUND_QUOTA_SCOPE_V1','PER_SHARD_REPAIR_SCOPE_V1'
    )),
    prior_receipt_json TEXT NOT NULL CHECK(json_valid(prior_receipt_json)),
    prior_receipt_hash TEXT NOT NULL CHECK(
        length(prior_receipt_hash)=64
        AND prior_receipt_hash NOT GLOB '*[^0-9a-f]*'
    ),
    blocked_operation_ids_json TEXT NOT NULL CHECK(json_valid(blocked_operation_ids_json)),
    created_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE(job_id,reason)
);

-- At most two safe validation repairs are allowed for any one bounded shard.
-- The previous job-level counter is retained for backward compatibility and
-- records the maximum ordinal used; this table is the canonical total ledger.
CREATE TABLE IF NOT EXISTS auto_knowledge_repair_reservations (
    job_id TEXT NOT NULL REFERENCES auto_knowledge_jobs(id) ON DELETE RESTRICT,
    stage TEXT NOT NULL CHECK(stage IN ('SECTION_MAP','TEACHING_SPEC')),
    shard_key TEXT NOT NULL,
    ordinal INTEGER NOT NULL CHECK(ordinal BETWEEN 1 AND 2),
    operation_id TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    PRIMARY KEY(job_id,stage,shard_key,ordinal)
);

-- Preserve repair operations produced before this migration. Operation ids are
-- generated by this service and the suffix is therefore a stable audit field.
INSERT OR IGNORE INTO auto_knowledge_repair_reservations(
    job_id,stage,shard_key,ordinal,operation_id,created_at
)
SELECT
    job_id,stage,shard_key,CAST(substr(operation_id,-1) AS INTEGER),
    operation_id,created_at
FROM auto_knowledge_model_attempts
WHERE operation_id GLOB '*-r[12]';

CREATE TRIGGER IF NOT EXISTS immutable_auto_knowledge_recovery_update
BEFORE UPDATE ON auto_knowledge_job_recovery_receipts
BEGIN
    SELECT RAISE(ABORT, 'Automatic-map recovery receipts are immutable');
END;

CREATE TRIGGER IF NOT EXISTS immutable_auto_knowledge_recovery_delete
BEFORE DELETE ON auto_knowledge_job_recovery_receipts
BEGIN
    SELECT RAISE(ABORT, 'Automatic-map recovery receipts are immutable');
END;

INSERT OR IGNORE INTO schema_migrations(version,name)
VALUES(44,'automatic knowledge-map background budget scope');
